"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.StargateRouterAbi__factory = exports.ERC20Abi__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var ERC20Abi__factory_1 = require("./ERC20Abi__factory");
Object.defineProperty(exports, "ERC20Abi__factory", { enumerable: true, get: function () { return ERC20Abi__factory_1.ERC20Abi__factory; } });
var StargateRouterAbi__factory_1 = require("./StargateRouterAbi__factory");
Object.defineProperty(exports, "StargateRouterAbi__factory", { enumerable: true, get: function () { return StargateRouterAbi__factory_1.StargateRouterAbi__factory; } });
