import {StargateBlockchainType} from "./providers";
import {TokenType} from "./tokens";

export const ChainPaths: any = {
    [StargateBlockchainType.Ethereum]: {
        [TokenType.USDC]: ['ETHEREUM-USDT', 'BSC-BUSD', 'BSC-USDT', 'AVALANCHE-USDC', 'AVALANCHE-USDT', 'POLYGON-USDC', 'POLYGON-USDT', 'ARBITRUM-USDC', 'ARBITRUM-USDT', 'OPTIMISM-USDC', 'FANTOM-USDC'],
        [TokenType.USDT]: ['ETHEREUM-USDT', 'BSC-BUSD', 'BSC-USDT', 'AVALANCHE-USDC', 'AVALANCHE-USDT', 'POLYGON-USDC', 'POLYGON-USDT', 'ARBITRUM-USDC', 'ARBITRUM-USDT', 'OPTIMISM-USDC', 'FANTOM-USDC'],
        [TokenType.DAI]: ['POLYGON-DAI', 'OPTIMISM-DAI'],
        [TokenType.FRAX]: ['AVALANCHE-FRAX', 'ARBITRUM-FRAX', 'OPTIMISM-FRAX'],
        [TokenType.USDD]: ['BSC-USDD'],
        [TokenType.SGETH]: ['ARBITRUM-SGETH', 'OPTIMISM-SGETH'],
        [TokenType.SUSD]: ['OPTIMISM-SUSD'],
        [TokenType.LUSD]: ['ARBITRUM-LUSD', 'OPTIMISM-LUSD'],
        [TokenType.MAI]: ['BSC-MAI', 'AVALANCHE-MAI', 'POLYGON-MAI', 'ARBITRUM-MAI', 'OPTIMISM-MAI'],
        [TokenType.METIS]: ['BSC-METIS', 'METIS-METIS'],
        [TokenType.mUSDT]: ['METIS-m.USDT'],
    },
    [StargateBlockchainType.BnbChain]: {
        [TokenType.BUSD]: ['ETHEREUM-USDC', 'ETHEREUM-USDT', 'AVALANCHE-USDC', 'AVALANCHE-USDT', 'POLYGON-USDC', 'POLYGON-USDT', 'ARBITRUM-USDC', 'ARBITRUM-USDT', 'OPTIMISM-USDC', 'FANTOM-USDC'],
        [TokenType.USDT]: ['ETHEREUM-USDC', 'ETHEREUM-USDT', 'AVALANCHE-USDC', 'AVALANCHE-USDT', 'POLYGON-USDC', 'POLYGON-USDT', 'ARBITRUM-USDC', 'ARBITRUM-USDT', 'OPTIMISM-USDC', 'FANTOM-USDC'],
        [TokenType.USDD]: ['ETHEREUM-USDD'],
        [TokenType.MAI]: ['ETHEREUM-MAI', 'AVALANCHE-MAI', 'POLYGON-MAI', 'ARBITRUM-MAI', 'OPTIMISM-MAI'],
        [TokenType.METIS]: ['ETHEREUM-METIS', 'METIS-METIS'],
        [TokenType.mUSDT]: ['METIS-m.USDT'],
    },
    [StargateBlockchainType.Avalanche]: {
        [TokenType.USDC]: ['ETHEREUM-USDC', 'ETHEREUM-USDT', 'BSC-BUSD', 'BSC-USDT', 'POLYGON-USDC', 'POLYGON-USDT', 'ARBITRUM-USDC', 'ARBITRUM-USDT', 'OPTIMISM-USDC', 'FANTOM-USDC'],
        [TokenType.USDT]: ['ETHEREUM-USDC', 'ETHEREUM-USDT', 'BSC-BUSD', 'BSC-USDT', 'POLYGON-USDC', 'POLYGON-USDT', 'ARBITRUM-USDC', 'ARBITRUM-USDT', 'OPTIMISM-USDC', 'FANTOM-USDC'],
        [TokenType.FRAX]: ['ETHEREUM-FRAX', 'ARBITRUM-FRAX', 'OPTIMISM-FRAX'],
        [TokenType.MAI]: ['ETHEREUM-MAI', 'BSC-MAI', 'POLYGON-MAI', 'ARBITRUM-MAI', 'OPTIMISM-MAI'],
        [TokenType.mUSDT]: ['METIS-m.USDT']
    },
    [StargateBlockchainType.Polygon]: {
        [TokenType.USDC]: ['ETHEREUM-USDC', 'ETHEREUM-USDT', 'BSC-BUSD', 'BSC-USDT', 'AVALANCHE-USDC', 'AVALANCHE-USDT', 'ARBITRUM-USDC', 'ARBITRUM-USDT', 'OPTIMISM-USDC', 'FANTOM-USDC'],
        [TokenType.USDT]: ['ETHEREUM-USDC', 'ETHEREUM-USDT', 'BSC-BUSD', 'BSC-USDT', 'AVALANCHE-USDC', 'AVALANCHE-USDT', 'ARBITRUM-USDC', 'ARBITRUM-USDT', 'OPTIMISM-USDC', 'FANTOM-USDC'],
        [TokenType.DAI]: ['ETHEREUM-DAI', 'OPTIMISM-DAI'],
        [TokenType.MAI]: ['OPTIMISM-MAI', 'ARBITRUM-MAI', 'AVALANCHE-MAI', 'BSC-MAI', 'ETHEREUM-MAI'],
    },
    [StargateBlockchainType.Arbitrum]: {
        [TokenType.USDC]: ['ETHEREUM-USDC', 'ETHEREUM-USDT', 'BSC-BUSD', 'BSC-USDT', 'AVALANCHE-USDC', 'AVALANCHE-USDT', 'POLYGON-USDC', 'POLYGON-USDT', 'OPTIMISM-USDC', 'FANTOM-USDC'],
        [TokenType.USDT]: ['ETHEREUM-USDC', 'ETHEREUM-USDT', 'BSC-BUSD', 'BSC-USDT', 'AVALANCHE-USDC', 'AVALANCHE-USDT', 'POLYGON-USDC', 'POLYGON-USDT', 'OPTIMISM-USDC', 'FANTOM-USDC'],
        [TokenType.FRAX]: ['ETHEREUM-FRAX', 'AVALANCHE-FRAX', 'OPTIMISM-FRAX'],
        [TokenType.SGETH]: ['ETHEREUM-SGETH', 'OPTIMISM-SGETH'],
        [TokenType.LUSD]: ['ETHEREUM-LUSD', 'OPTIMISM-LUSD'],
        [TokenType.MAI]: ['OPTIMISM-MAI', 'POLYGON-MAI', 'AVALANCHE-MAI', 'BSC-MAI', 'ETHEREUM-MAI'],
    },
    [StargateBlockchainType.Optimism]: {
        [TokenType.USDC]: ['ETHEREUM-USDC', 'ETHEREUM-USDT', 'BSC-BUSD', 'BSC-USDT', 'AVALANCHE-USDC', 'AVALANCHE-USDT', 'POLYGON-USDC', 'POLYGON-USDT', 'ARBITRUM-USDC', 'ARBITRUM-USDT', 'FANTOM-USDC'],
        [TokenType.DAI]: ['ETHEREUM-DAI', 'POLYGON-DAI'],
        [TokenType.FRAX]: ['ETHEREUM-FRAX', 'AVALANCHE-FRAX', 'ARBITRUM-FRAX'],
        [TokenType.SGETH]: ['ETHEREUM-SGETH', 'ARBITRUM-SGETH'],
        [TokenType.SUSD]: ['ETHEREUM-SUSD'],
        [TokenType.LUSD]: ['ETHEREUM-LUSD', 'ARBITRUM-LUSD'],
        [TokenType.MAI]: ['ARBITRUM-MAI', 'POLYGON-MAI', 'AVALANCHE-MAI', 'BSC-MAI', 'ETHEREUM-MAI'],
    },
    [StargateBlockchainType.Fantom]: {
        [TokenType.USDC]: ['ETHEREUM-USDC', 'ETHEREUM-USDT', 'BSC-BUSD', 'BSC-USDT', 'AVALANCHE-USDC', 'AVALANCHE-USDT', 'POLYGON-USDC', 'POLYGON-USDT', 'ARBITRUM-USDC', 'ARBITRUM-USDT', 'OPTIMISM-USDC'],
    },
    [StargateBlockchainType.Metis]: {
        [TokenType.METIS]: ['ETHEREUM-METIS', 'BSC-METIS'],
        [TokenType.mUSDT]: ['ETHEREUM-m.USDT', 'BSC-m.USDT', 'AVALANCHE-m.USDT'],
    },
}